import { existsSync, readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { randomUUID } from 'node:crypto';
import type { AIEventProvider } from './AIEventProvider';
import type { AIEventGenerationInput, AIEventOutput } from '@/domain/types/ai';
import type { EventCard } from '@/domain/types/game';
import { buildEventGenerationPrompt } from './prompts/eventGenerationPrompt';
import { safetyFilterService } from '@/domain/services/SafetyFilterService';
import { generateId } from '@/lib/id';

interface ChatCompletionResponse {
  choices?: Array<{
    message?: {
      content?: string;
    };
  }>;
}

export class OpenAICompatibleEventProvider implements AIEventProvider {
  name = 'openai-compatible';

  async generateEvent(input: AIEventGenerationInput): Promise<AIEventOutput> {
    const apiKey = getApiKey();
    if (!apiKey) {
      throw new Error(
        'Missing OPENAI_COMPATIBLE_API_KEY or OPENAI_API_KEY. Set it in .env.local.',
      );
    }

    const baseUrl = normalizeBaseUrl(
      process.env.OPENAI_COMPATIBLE_BASE_URL ??
        process.env.OPENAI_BASE_URL ??
        'https://api.openai.com/v1',
    );
    const model =
      process.env.OPENAI_COMPATIBLE_MODEL ??
      process.env.OPENAI_MODEL ??
      'gpt-4.1-mini';

    const url = new URL(`${baseUrl}/chat/completions`);
    url.searchParams.set('request_id', randomUUID());

    const res = await fetch(url, {
      method: 'POST',
      headers: {
        Authorization: `Bearer ${apiKey}`,
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        model,
        temperature: 0.7,
        messages: [
          {
            role: 'system',
            content:
              'Return only valid JSON for one educational anti-fraud game event. Do not include markdown.',
          },
          {
            role: 'user',
            content: buildEventGenerationPrompt(input),
          },
        ],
      }),
    });

    if (!res.ok) {
      const errorText = await res.text();
      throw new Error(`OpenAI-compatible provider failed: ${res.status} ${errorText}`);
    }

    const data = (await res.json()) as ChatCompletionResponse;
    const content = data.choices?.[0]?.message?.content;
    if (!content) {
      throw new Error('OpenAI-compatible provider returned an empty response.');
    }

    const event = normalizeGeneratedEvent(parseEventCard(content), input);
    const filterResult = safetyFilterService.filterEvent(event);
    if (!filterResult.passed) {
      throw new Error(`Safety filter blocked event: ${filterResult.blockedReasons.join(', ')}`);
    }

    return {
      event: filterResult.filteredEvent,
      provider: this.name,
      confidence: 0.7,
      reasoning: `Generated by ${model} via OpenAI-compatible chat completions.`,
    };
  }
}

function normalizeBaseUrl(url: string): string {
  return url.replace(/\/+$/, '');
}

function getApiKey(): string | null {
  const envKey = process.env.OPENAI_COMPATIBLE_API_KEY ?? process.env.OPENAI_API_KEY;
  if (envKey?.trim()) return envKey.trim();

  if (process.env.NODE_ENV === 'production') return null;

  const candidates = [
    resolve(process.cwd(), '..', 'api_key.txt'),
    resolve(process.cwd(), 'api_key.txt'),
  ];
  for (const file of candidates) {
    if (!existsSync(file)) continue;
    const key = readFileSync(file, 'utf8')
      .split(/\r?\n/)
      .map((line) => line.trim())
      .filter(Boolean)
      .map((line) => {
        const equalIndex = line.indexOf('=');
        return equalIndex >= 0 ? line.slice(equalIndex + 1).trim() : line;
      })
      .sort((a, b) => b.length - a.length)[0];
    if (key) return key;
  }

  return null;
}

function parseEventCard(raw: string): EventCard {
  const jsonText = extractJson(raw);
  return JSON.parse(jsonText) as EventCard;
}

function extractJson(raw: string): string {
  const trimmed = raw.trim();
  if (trimmed.startsWith('{') && trimmed.endsWith('}')) return trimmed;

  const fenced = trimmed.match(/```(?:json)?\s*([\s\S]*?)```/i);
  if (fenced?.[1]) return fenced[1].trim();

  const start = trimmed.indexOf('{');
  const end = trimmed.lastIndexOf('}');
  if (start >= 0 && end > start) return trimmed.slice(start, end + 1);

  throw new Error('OpenAI-compatible provider did not return JSON.');
}

function normalizeGeneratedEvent(event: EventCard, input: AIEventGenerationInput): EventCard {
  return {
    ...event,
    id: event.id || generateId('ai_event'),
    phase: 'playing',
    actions: Array.isArray(event.actions) ? event.actions : [],
    nextEventRules: Array.isArray(event.nextEventRules) ? event.nextEventRules : [],
    defaultNextEventId: event.defaultNextEventId ?? 'E09',
    teachingPoint:
      event.teachingPoint ??
      `围绕 ${input.teachingGoal} 的反诈识别练习：先核实官方渠道再行动。`,
  };
}

export const openAICompatibleEventProvider = new OpenAICompatibleEventProvider();
